server:
  port: 8761
<<<<<<< Updated upstream
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: ${EUREKA_HOST_NAME:eureka-server}
=======

spring:
  application:
    name: eureka-server

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://config-server:8888}
  cloud:
    config:
      fail-fast: false
>>>>>>> Stashed changes
